version: '3'
services:
  # why this doesn't work..
  web:
    build: .
    command: bundle exec rails s -p 4000
    ports:
      - "4000:4000"
  # TODO for db services
  # db:
  #   image: mariadb
  #   volumes: 
  #     - ./dumps/db:/var/lib/mariadb/data